<?php
/**
 * Copyright © 2023 Line. All rights reserved.
 */

/**
 * @var Line\Payment\Block\Form $block
 * @var Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @var Magento\Framework\Escaper $escaper
 */
?>
<fieldset class="admin__fieldset payment-method" id="payment_form_<?= $escaper->escapeHtml($block->getMethodCode()) ?>">
    <div class="admin__field _required">
        <label for="po_number" class="admin__field-label">
            <span><?= $escaper->escapeHtml(__('Information')) ?></span>
        </label>
        <div class="admin__field-control">
            <?= /* @noEscape */ $block->getInfoData('additional_information') ?>
        </div>
    </div>
</fieldset>
